In [ ]:
# Importing required libraries

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from surprise import Reader, Dataset, SVD, accuracy
from surprise.model_selection import train_test_split

## Pre-Processing

In [ ]:
# Adjusting row column settings

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 500)
pd.set_option('display.expand_frame_repr', False)

In [ ]:
# Loading the dataset

movie_df = pd.read_csv('movie.csv')
rating_df = pd.read_csv('rating.csv')

In [ ]:
# Checking No. of Unique Values in the Datasets

movie_df.nunique()

movieId    27278
title      27262
genres      1342
dtype: int64

In [ ]:
rating_df.nunique()

userId         138493
movieId         26744
rating             10
timestamp    15351121
dtype: int64

In [ ]:
# Reducing the rating dataset

unique_users = rating_df['userId'].unique()
half_users = np.random.choice(unique_users, size=round(0.5*(len(unique_users))), replace=False)
half_rating_df = rating_df[rating_df['userId'].isin(half_users)]
print("Original DataFrame shape:", rating_df.shape)
print("New DataFrame shape after removing half the users:", half_rating_df.shape)

Original DataFrame shape: (20000263, 4)
New DataFrame shape after removing half the users: (9950537, 4)

In [ ]:
half_rating_df.head()

     userId  movieId  rating            timestamp
236       3        1     4.0  1999-12-11 13:36:47
237       3       24     3.0  1999-12-14 12:54:08
238       3       32     4.0  1999-12-11 13:14:07
239       3       50     5.0  1999-12-11 13:13:38
240       3      160     3.0  1999-12-14 12:54:08

In [ ]:
# Merging movie and rating datasets

df = movie_df.merge(half_rating_df, how="left", on="movieId")

In [ ]:
# Preliminary examination of the data set

def check_df(dataframe, head=5):
    print('##################### Shape #####################')
    print(dataframe.shape)
    print('##################### Types #####################')
    print(dataframe.dtypes)
    print('##################### Head #####################')
    print(dataframe.head(head))
    print('##################### Tail #####################')
    print(dataframe.tail(head))
    print('##################### NA #####################')
    print(dataframe.isnull().sum())
    print('##################### Quantiles #####################')
    print(dataframe['rating'].describe([0, 0.05, 0.50, 0.95, 0.99, 1]))

check_df(df)

##################### Shape #####################
(9953889, 6)
##################### Types #####################
movieId        int64
title         object
genres        object
userId       float64
rating       float64
timestamp     object
dtype: object
##################### Head #####################
   movieId             title                                       genres  userId  rating            timestamp
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy     3.0     4.0  1999-12-11 13:36:47
1        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy     6.0     5.0  1997-03-13 17:50:52
2        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy    10.0     4.0  1999-11-25 02:44:47
3        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy    14.0     4.5  2008-10-29 20:13:59
4        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy    19.0     5.0  1997-02-05 21:03:48
##################### Tail #####################
         movieId                          title                    genres    userId  rating            timestamp
9953884   131254   Kein Bund für's Leben (2007)                    Comedy       NaN     NaN                  NaN
9953885   131256  Feuer, Eis & Dosenbier (2002)                    Comedy       NaN     NaN                  NaN
9953886   131258             The Pirates (2014)                 Adventure   28906.0     2.5  2015-03-30 19:56:32
9953887   131260            Rentun Ruusu (2001)        (no genres listed)   65409.0     3.0  2015-03-30 19:57:46
9953888   131262               Innocence (2014)  Adventure|Fantasy|Horror  133047.0     4.0  2015-03-30 20:39:26
##################### NA #####################
movieId         0
title           0
genres          0
userId       3352
rating       3352
timestamp    3352
dtype: int64
##################### Quantiles #####################
count    9.950537e+06
mean     3.526011e+00
std      1.051657e+00
min      5.000000e-01
0%       5.000000e-01
5%       1.500000e+00
50%      3.500000e+00
95%      5.000000e+00
99%      5.000000e+00
100%     5.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

## Creating a Pivot Table

In [ ]:
# Step-1: Calculate the total number of ratings cast for each movie.

rating_counts = pd.DataFrame(df["title"].value_counts())
rating_counts.head(10)

                                           title
Pulp Fiction (1994)                        33624
Forrest Gump (1994)                        32953
Silence of the Lambs, The (1991)           31663
Shawshank Redemption, The (1994)           31514
Jurassic Park (1993)                       29743
Star Wars: Episode IV - A New Hope (1977)  27249
Braveheart (1995)                          26779
Terminator 2: Judgment Day (1991)          26099
Matrix, The (1999)                         25608
Schindler's List (1993)                    25080

In [ ]:
rating_counts.shape

(27262, 1)

In [ ]:
# Step-2: Store the names of films with less than 500 total votes in rare_movies and remove them from the dataset.

rare_movies = rating_counts[rating_counts['title'] <= 500].index
common_movies = df[~df["title"].isin(rare_movies)]
common_movies.head()

   movieId             title                                       genres  userId  rating            timestamp
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy     3.0     4.0  1999-12-11 13:36:47
1        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy     6.0     5.0  1997-03-13 17:50:52
2        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy    10.0     4.0  1999-11-25 02:44:47
3        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy    14.0     4.5  2008-10-29 20:13:59
4        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy    19.0     5.0  1997-02-05 21:03:48

common_movies = df

In [ ]:
common_movies.shape

(8831534, 6)

In [ ]:
len(pd.unique(common_movies['title']))

3129

In [ ]:
# Step-3: Create a pivot table for dataframe with userIDs in index, movieIds in columns and ratings as values.

user_movie_df = common_movies.pivot_table(index=["userId"], columns=["movieId"], values="rating")
user_movie_df.head()

movieId  1       2       3       4       5       6       7       8       9       10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      34      35      36      39      41      42      43      44      45      46      47      48      50      52      57      58      60      61      62      63      64      65      66      68      69      70      71      72      73      74      76      78      79      81      82      85      86      88      89      92      93      94      95      97      100     101     102     103     104     105     107     110     111     112     113     117     118     122     123     125     126     132     135     140     141     144     145     147     149     150     151     153     154     155     156     157     158     159     160     161     162     163     164     165     168     169     170     171     172     173     174     175     176     177     179     180     181     185     186     188     191     193     194     195     196     198     199     203     204     205     207     208     213     215     216     217     218     222     223     224     225     227     229     230     231     232     233     234     235     236     237     239     242     246     247     248     249     252     253     255     256     257     258     259     260     261     262     265     266     267     270     271     272     273     274     275     276     277     278     280     281     282     288     289     290     292     293     296     299     300     302     303     305     306     307     308     312     313     314     315     316     317     318     319     322     325     326     327     328     329     330     332     333     334     337     338     339     340     342     344     345     346     347     348     349     350     351     352     353     354     355     356     357     358     360     361     362     364     365     366     367     368     369     370     371     372     373     374     376     377     378     379     380     381     382     383     393     405     407     410     412     413     415     416     417     419     420     421     422     423     426     427     428     429     431     432     433     434     435     436     437     438     440     441     442     444     445     446     448     450     452     454     455     457     458     459     464     466     468     469     471     473     474     475     477     479     480     481     482     485     489     490     491     492     493     494     497     500     501     502     504     505     506     507     508     509     511     512     514     515     516     517     518     519     520     521     522     524     527     529     531     532     533     534     535     537     538     539     540     541     542     543     544     546     548     549     550     551     552     553     555     556     558     562     569     574     575     581     585     586     587     588     589     590     592     593     594     595     596     597     599     605     606     608     609     610     611     612     613     616     627     628     631     635     637     639     640     647     648     650     653     656     661     662     663     665     667     671     673     674     678     680     688     691     694     697     700     704     707     708     709     710     711     714     719     720     724     725     728     733     735     736     737     741     742     743     745     747     748     750     761     762     765     766     778     780     781     782     783     784     785     786     788     798     799     800     801     802     804     805     809     810     818     828     829     830     832     833     836     837     838     839     842     848     849     851     852     858     861     866     879     880     881     886     891     892     898     899     900     901     902     903     904     905     906     908     909     910     911     912     913     914     915     916     917     918     919     920     921     922     923     924     926     928     930     931     932     933     934     936     938     940     942     943     944     945     946     947     948     949     950     951     952     953     954     955     965     968     969     971     986     991     994     996     999     1003    1004    1005    1006    1007    1009    1010    1011    1012    1013    1014    1015    1016    1017    1018    1019    1020    1021    1022    1023    1024    1025    1027    1028    1029    1030    1031    1032    1033    1034    1035    1036    1037    1041    1042    1043    1046    1047    1049    1050    1051    1057    1059    1060    1061    1064    1066    1073    1077    1078    1079    1080    1081    1082    1083    1084    1085    1086    1088    1089    1090    1091    1092    1093    1094    1095    1096    1097    1099    1100    1101    1103    1104    1111    1113    1120    1124    1125    1126    1127    1128    1129    1130    1131    1132    1135    1136    1147    1148    1150    1161    1171    1172    1173    1175    1176    1177    1178    1179    1183    1184    1185    1186    1187    1188    1189    1190    1191    1192    1193    1194    1196    1197    1198    1199    1200    1201    1202    1203    1204    1206    1207    1208    1209    1210    1211    1212    1213    1214    1215    1216    1217    1218    1219    1220    1221    1222    1223    1224    1225    1226    1227    1228    1230    1231    1232    1233    1234    1235    1236    1237    1238    1240    1241    1242    1243    1244    1245    1246    1247    1248    1249    1250    1251    1252    1253    1254    1255    1256    1257    1258    1259    1260    1261    1262    1263    1264    1265    1266    1267    1268    1269    1270    1271    1272    1273    1274    1275    1276    1277    1278    1279    1280    1281    1282    1283    1284    1285    1286    1287    1288    1289    1290    1291    1292    1293    1295    1296    1297    1298    1299    1300    1301    1302    1303    1304    1305    1306    1307    1320    1321    1327    1333    1334    1339    1340    1342    1343    1344    1345    1346    1347    1348    1350    1353    1354    1356    1357    1358    1359    1361    1363    1365    1366    1367    1370    1371    1372    1373    1374    1375    1376    1377    1378    1379    1380    1381    1385    1387    1388    1389    1390    1391    1392    1393    1394    1395    1396    1399    1401    1405    1407    1408    1409    1411    1414    1416    1419    1422    1425    1429    1431    1432    1438    1441    1445    1446    1449    1453    1457    1459    1461    1464    1466    1468    1474    1476    1479    1480    1483    1485    1487    1488    1498    1499    1500    1503    1513    1515    1517    1518    1527    1537    1541    1542    1544    1552    1554    1556    1562    1566    1569    1573    1580    1584    1586    1587    1588    1589    1590    1591    1592    1593    1594    1597    1603    1608    1610    1611    1614    1615    1616    1617    1619    1620    1625    1627    1633    1635    1639    1641    1643    1644    1645    1648    1649    1653    1658    1660    1663    1665    1667    1672    1673    1674    1676    1678    1680    1681    1682    1683    1687    1688    1689    1690    1693    1694    1699    1701    1702    1704    1707    1711    1713    1717    1719    1721    1722    1726    1727    1729    1730    1732    1734    1735    1747    1748    1752    1753    1754    1760    1762    1769    1772    1777    1779    1783    1784    1785    1792    1794    1797    1799    1801    1805    1806    1809    1810    1821    1831    1833    1834    1835    1836    1840    1845    1848    1858    1862    1863    1866    1873    1875    1876    1882    1883    1884    1885    1888    1889    1892    1894    1895    1897    1907    1909    1911    1912    1913    1914    1916    1917    1918    1920    1921    1923    1924    1927    1931    1938    1939    1944    1945    1946    1947    1948    1949    1950    1951    1952    1953    1954    1955    1956    1957    1958    1959    1960    1961    1962    1963    1964    1965    1966    1967    1968    1969    1970    1971    1972    1973    1974    1975    1976    1977    1978    1979    1980    1981    1982    1983    1984    1991    1992    1994    1995    1996    1997    1998    1999    2000    2001    2002    2003    2004    2005    2006    2009    2010    2011    2012    2013    2014    2015    2018    2019    2020    2021    2022    2023    2025    2026    2028    2033    2034    2036    2038    2042    2043    2046    2048    2050    2052    2053    2054    2058    2059    2060    2064    2065    2066    2067    2068    2069    2070    2071    2072    2076    2077    2078    2080    2081    2082    2083    2085    2087    2088    2089    2090    2091    2092    2093    2094    2096    2097    2099    2100    2102    2105    2106    2107    2108    2109    2110    2111    2112    2114    2115    2116    2117    2118    2119    2120    2121    2122    2123    2124    2125    2126    2130    2132    2133    2134    2135    2136    2137    2138    2139    2140    2141    2142    2143    2144    2145    2146    2147    2148    2150    2151    2153    2154    2155    2159    2160    2161    2162    2163    2167    2169    2171    2174    2176    2178    2181    2183    2184    2186    2188    2193    2194    2195    2202    2203    2206    2208    2212    2231    2232    2236    2240    2243    2245    2247    2248    2249    2252    2253    2259    2261    2262    2263    2266    2268    2269    2273    2278    2279    2282    2287    2288    2289    2290    2291    2294    2296    2297    2300    2301    2302    2303    2311    2312    2313    2315    2316    2318    2320    2321    2322    2324    2325    2328    2329    2331    2333    2334    2335    2336    2337    2338    2340    2344    2346    2348    2349    2351    2352    2353    2354    2355    2356    2357    2359    2360    2361    2363    2366    2367    2369    2371    2372    2373    2374    2375    2376    2377    2378    2379    2380    2381    2382    2383    2384    2387    2389    2390    2391    2392    2393    2394    2395    2396    2398    2399    2401    2402    2403    2404    2405    2406    2407    2408    2409    2410    2411    2412    2413    2414    2416    2420    2421    2422    2423    2424    2427    2428    2429    2431    2432    2433    2436    2439    2442    2443    2447    2448    2450    2453    2454    2455    2456    2457    2459    2463    2467    2468    2469    2470    2471    2473    2474    2476    2478    2485    2488    2490    2496    2497    2501    2502    2504    2505    2506    2511    2513    2517    2518    2520    2524    2527    2528    2529    2530    2531    2532    2533    2539    2540    2541    2542    2546    2549    2550    2551    2553    2555    2558    2560    2561    2565    2567    2568    2571    2572    2574    2575    2579    2580    2581    2583    2594    2596    2598    2599    2600    2605    2606    2611    2612    2613    2615    2616    2617    2618    2622    2628    2633    2639    2640    2641    2642    2643    2644    2648    2657    2660    2662    2664    2668    2670    2671    2672    2676    2677    2683    2686    2687    2688    2690    2692    2693    2694    2696    2699    2700    2701    2702    2706    2707    2709    2710    2712    2713    2716    2717    2718    2719    2720    2722    2723    2724    2726    2728    2729    2730    2731    2732    2734    2735    2736    2739    2745    2746    2747    2750    2759    2761    2762    2763    2764    2770    2771    2772    2779    2787    2788    2789    2791    2792    2793    2794    2795    2796    2797    2798    2799    2802    2803    2804    2805    2806    2807    2808    2810    2815    2819    2822    2826    2827    2829    2836    2840    2841    2843    2846    2852    2857    2858    2859    2860    2861    2862    2863    2866    2867    2870    2871    2872    2875    2877    2881    2883    2888    2889    2890    2891    2901    2902    2905    2906    2907    2908    2912    2915    2916    2917    2918    2919    2920    2921    2922    2924    2926    2929    2932    2935    2936    2940    2941    2942    2944    2946    2947    2948    2949    2950    2951    2952    2953    2959    2961    2966    2968    2970    2971    2973    2976    2985    2986    2987    2989    2990    2991    2993    2995    2997    3000    3004    3005    3006    3007    3011    3015    3016    3018    3019    3020    3022    3030    3032    3033    3034    3035    3036    3037    3039    3040    3044    3051    3052    3053    3054    3060    3061    3062    3063    3066    3067    3068    3070    3071    3072    3074    3075    3077    3079    3081    3082    3083    3087    3088    3089    3090    3091    3093    3095    3097    3098    3099    3100    3101    3102    3104    3105    3107    3108    3111    3113    3114    3125    3129    3130    3134    3135    3142    3145    3146    3147    3148    3152    3153    3155    3156    3157    3159    3160    3163    3167    3168    3169    3173    3174    3175    3176    3177    3178    3179    3181    3185    3186    3189    3194    3196    3197    3198    3200    3201    3203    3204    3208    3210    3213    3219    3238    3243    3244    3246    3247    3248    3249    3250    3251    3252    3253    3254    3255    3256    3257    3258    3259    3260    3261    3262    3263    3264    3265    3266    3267    3268    3269    3270    3271    3272    3273    3274    3275    3285    3296    3298    3300    3301    3307    3308    3316    3317    3324    3328    3334    3342    3347    3354    3355    3358    3359    3360    3361    3362    3363    3364    3365    3384    3386    3387    3388    3392    3394    3396    3397    3398    3404    3408    3409    3418    3420    3421    3424    3426    3429    3430    3435    3438    3439    3440    3441    3444    3448    3450    3451    3452    3461    3462    3466    3467    3468    3469    3471    3476    3477    3478    3479    3480    3481    3483    3484    3489    3494    3498    3499    3503    3504    3505    3507    3508    3510    3512    3513    3515    3519    3521    3524    3525    3526    3527    3528    3529    3534    3535    3536    3538    3543    3545    3546    3548    3549    3551    3552    3554    3555    3556    3564    3565    3566    3576    3578    3591    3593    3594    3598    3608    3614    3615    3616    3617    3618    3623    3624    3629    3633    3635    3638    3639    3646    3649    3654    3668    3671    3675    3676    3677    3681    3682    3683    3684    3685    3686    3688    3693    3697    3698    3699    3700    3701    3702    3703    3704    3705    3706    3707    3708    3712    3717    3723    3727    3729    3730    3733    3735    3740    3741    3742    3744    3745    3751    3752    3753    3754    3755    3760    3763    3764    3770    3783    3784    3785    3786    3788    3791    3793    3798    3799    3801    3802    3809    3811    3812    3814    3819    3821    3824    3825    3826    3827    3831    3836    3841    3844    3852    3861    3863    3864    3868    3869    3871    3873    3877    3879    3882    3889    3893    3896    3897    3908    3910    3911    3916    3917    3918    3925    3927    3930    3932    3946    3948    3949    3950    3952    3953    3959    3967    3968    3969    3972    3973    3977    3978    3979    3980    3981    3983    3984    3986    3987    3988    3991    3993    3994    3996    3997    3998    3999    4002    4005    4006    4007    4008    4010    4011    4014    4015    4016    4017    4018    4019    4020    4022    4023    4025    4027    4029    4030    4031    4033    4034    4036    4037    4039    4040    4041    4047    4052    4054    4056    4061    4062    4066    4069    4084    4085    4086    4090    4091    4102    4103    4104    4105    4117    4121    4124    4128    4132    4133    4144    4148    4149    4155    4159    4161    4167    4205    4207    4210    4211    4214    4215    4220    4223    4225    4226    4228    4232    4234    4235    4238    4239    4246    4247    4248    4254    4255    4262    4265    4270    4275    4280    4291    4292    4299    4306    4308    4310    4321    4322    4326    4327    4329    4333    4340    4343    4344    4349    4351    4356    4359    4361    4366    4367    4368    4369    4370    4372    4378    4380    4386    4387    4388    4396    4406    4424    4427    4443    4446    4447    4448    4464    4465    4467    4474    4478    4487    4488    4489    4499    4506    4508    4519    4533    4535    4544    4545    4546    4553    4558    4564    4571    4572    4587    4616    4621    4623    4638    4639    4641    4642    4643    4654    4661    4673    4677    4678    4679    4681    4700    4701    4703    4713    4718    4719    4720    4728    4733    4734    4735    4744    4748    4754    4757    4776    4787    4799    4809    4814    4815    4816    4821    4823    4835    4844    4846    4848    4855    4857    4865    4866    4867    4873    4874    4876    4878    4880    4881    4886    4887    4889    4890    4896    4901    4902    4903    4914    4936    4941    4951    4954    4958    4963    4967    4970    4973    4974    4975    4978    4979    4980    4990    4992    4993    4994    4995    5008    5009    5010    5013    5014    5015    5016    5025    5026    5027    5040    5047    5049    5055    5060    5064    5065    5066    5072    5093    5103    5107    5108    5110    5120    5128    5135    5139    5146    5147    5151    5152    5159    5171    5218    5219    5220    5222    5225    5247    5254    5265    5266    5267    5283    5291    5292    5293    5294    5296    5299    5303    5308    5309    5312    5313    5316    5319    5329    5349    5364    5377    5378    5380    5388    5391    5400    5401    5415    5418    5419    5420    5421    5444    5445    5446    5449    5452    5459    5463    5464    5478    5479    5481    5500    5502    5504    5505    5507    5508    5524    5528    5530    5540    5541    5572    5574    5577    5602    5608    5617    5618    5620    5621    5630    5650    5666    5668    5669    5673    5679    5690    5693    5747    5782    5784    5785    5791    5803    5810    5812    5816    5872    5876    5878    5881    5882    5899    5900    5902    5903    5941    5943    5944    5945    5952    5954    5955    5956    5957    5959    5970    5971    5989    5991    5992    5995    6001    6003    6006    6016    6058    6059    6062    6093    6104    6155    6156    6157    6166    6184    6187    6188    6212    6213    6214    6218    6238    6242    6250    6264    6281    6283    6286    6287    6294    6296    6297    6299    6301    6303    6305    6322    6323    6331    6333    6350    6365    6367    6370    6373    6377    6378    6380    6383    6385    6440    6461    6482    6502    6503    6534    6535    6537    6538    6539    6541    6548    6550    6552    6564    6565    6586    6593    6595    6615    6617    6618    6620    6639    6645    6659    6662    6663    6664    6669    6707    6708    6709    6711    6724    6731    6753    6754    6755    6764    6765    6773    6774    6787    6791    6793    6796    6807    6808    6810    6857    6863    6867    6870    6873    6874    6879    6880    6881    6888    6890    6893    6932    6934    6936    6942    6944    6947    6952    6953    6954    6957    6966    6979    6987    6993    6996    7000    7001    7004    7007    7013    7018    7022    7027    7034    7036    7044    7046    7063    7073    7076    7084    7090    7099    7101    7116    7121   

In [ ]:
user_movie_df.shape

(69246, 3133)

## Determining the movies watched by a selected user

In [ ]:
# Step-1: Choose a random user id.

target_user_id = 6

In [ ]:
# Step-2: Create a new dataframe named random_user_df consisting of observation units of the selected user.

target_user_df = user_movie_df[user_movie_df.index == target_user_id]
target_user_df.head()

movieId  1       2       3       4       5       6       7       8       9       10      11      12      13      14      15      16      17      18      19      20      21      22      23      24      25      26      27      28      29      30      31      32      34      35      36      39      41      42      43      44      45      46      47      48      50      52      57      58      60      61      62      63      64      65      66      68      69      70      71      72      73      74      76      78      79      81      82      85      86      88      89      92      93      94      95      97      100     101     102     103     104     105     107     110     111     112     113     117     118     122     123     125     126     132     135     140     141     144     145     147     149     150     151     153     154     155     156     157     158     159     160     161     162     163     164     165     168     169     170     171     172     173     174     175     176     177     179     180     181     185     186     188     191     193     194     195     196     198     199     203     204     205     207     208     213     215     216     217     218     222     223     224     225     227     229     230     231     232     233     234     235     236     237     239     242     246     247     248     249     252     253     255     256     257     258     259     260     261     262     265     266     267     270     271     272     273     274     275     276     277     278     280     281     282     288     289     290     292     293     296     299     300     302     303     305     306     307     308     312     313     314     315     316     317     318     319     322     325     326     327     328     329     330     332     333     334     337     338     339     340     342     344     345     346     347     348     349     350     351     352     353     354     355     356     357     358     360     361     362     364     365     366     367     368     369     370     371     372     373     374     376     377     378     379     380     381     382     383     393     405     407     410     412     413     415     416     417     419     420     421     422     423     426     427     428     429     431     432     433     434     435     436     437     438     440     441     442     444     445     446     448     450     452     454     455     457     458     459     464     466     468     469     471     473     474     475     477     479     480     481     482     485     489     490     491     492     493     494     497     500     501     502     504     505     506     507     508     509     511     512     514     515     516     517     518     519     520     521     522     524     527     529     531     532     533     534     535     537     538     539     540     541     542     543     544     546     548     549     550     551     552     553     555     556     558     562     569     574     575     581     585     586     587     588     589     590     592     593     594     595     596     597     599     605     606     608     609     610     611     612     613     616     627     628     631     635     637     639     640     647     648     650     653     656     661     662     663     665     667     671     673     674     678     680     688     691     694     697     700     704     707     708     709     710     711     714     719     720     724     725     728     733     735     736     737     741     742     743     745     747     748     750     761     762     765     766     778     780     781     782     783     784     785     786     788     798     799     800     801     802     804     805     809     810     818     828     829     830     832     833     836     837     838     839     842     848     849     851     852     858     861     866     879     880     881     886     891     892     898     899     900     901     902     903     904     905     906     908     909     910     911     912     913     914     915     916     917     918     919     920     921     922     923     924     926     928     930     931     932     933     934     936     938     940     942     943     944     945     946     947     948     949     950     951     952     953     954     955     965     968     969     971     986     991     994     996     999     1003    1004    1005    1006    1007    1009    1010    1011    1012    1013    1014    1015    1016    1017    1018    1019    1020    1021    1022    1023    1024    1025    1027    1028    1029    1030    1031    1032    1033    1034    1035    1036    1037    1041    1042    1043    1046    1047    1049    1050    1051    1057    1059    1060    1061    1064    1066    1073    1077    1078    1079    1080    1081    1082    1083    1084    1085    1086    1088    1089    1090    1091    1092    1093    1094    1095    1096    1097    1099    1100    1101    1103    1104    1111    1113    1120    1124    1125    1126    1127    1128    1129    1130    1131    1132    1135    1136    1147    1148    1150    1161    1171    1172    1173    1175    1176    1177    1178    1179    1183    1184    1185    1186    1187    1188    1189    1190    1191    1192    1193    1194    1196    1197    1198    1199    1200    1201    1202    1203    1204    1206    1207    1208    1209    1210    1211    1212    1213    1214    1215    1216    1217    1218    1219    1220    1221    1222    1223    1224    1225    1226    1227    1228    1230    1231    1232    1233    1234    1235    1236    1237    1238    1240    1241    1242    1243    1244    1245    1246    1247    1248    1249    1250    1251    1252    1253    1254    1255    1256    1257    1258    1259    1260    1261    1262    1263    1264    1265    1266    1267    1268    1269    1270    1271    1272    1273    1274    1275    1276    1277    1278    1279    1280    1281    1282    1283    1284    1285    1286    1287    1288    1289    1290    1291    1292    1293    1295    1296    1297    1298    1299    1300    1301    1302    1303    1304    1305    1306    1307    1320    1321    1327    1333    1334    1339    1340    1342    1343    1344    1345    1346    1347    1348    1350    1353    1354    1356    1357    1358    1359    1361    1363    1365    1366    1367    1370    1371    1372    1373    1374    1375    1376    1377    1378    1379    1380    1381    1385    1387    1388    1389    1390    1391    1392    1393    1394    1395    1396    1399    1401    1405    1407    1408    1409    1411    1414    1416    1419    1422    1425    1429    1431    1432    1438    1441    1445    1446    1449    1453    1457    1459    1461    1464    1466    1468    1474    1476    1479    1480    1483    1485    1487    1488    1498    1499    1500    1503    1513    1515    1517    1518    1527    1537    1541    1542    1544    1552    1554    1556    1562    1566    1569    1573    1580    1584    1586    1587    1588    1589    1590    1591    1592    1593    1594    1597    1603    1608    1610    1611    1614    1615    1616    1617    1619    1620    1625    1627    1633    1635    1639    1641    1643    1644    1645    1648    1649    1653    1658    1660    1663    1665    1667    1672    1673    1674    1676    1678    1680    1681    1682    1683    1687    1688    1689    1690    1693    1694    1699    1701    1702    1704    1707    1711    1713    1717    1719    1721    1722    1726    1727    1729    1730    1732    1734    1735    1747    1748    1752    1753    1754    1760    1762    1769    1772    1777    1779    1783    1784    1785    1792    1794    1797    1799    1801    1805    1806    1809    1810    1821    1831    1833    1834    1835    1836    1840    1845    1848    1858    1862    1863    1866    1873    1875    1876    1882    1883    1884    1885    1888    1889    1892    1894    1895    1897    1907    1909    1911    1912    1913    1914    1916    1917    1918    1920    1921    1923    1924    1927    1931    1938    1939    1944    1945    1946    1947    1948    1949    1950    1951    1952    1953    1954    1955    1956    1957    1958    1959    1960    1961    1962    1963    1964    1965    1966    1967    1968    1969    1970    1971    1972    1973    1974    1975    1976    1977    1978    1979    1980    1981    1982    1983    1984    1991    1992    1994    1995    1996    1997    1998    1999    2000    2001    2002    2003    2004    2005    2006    2009    2010    2011    2012    2013    2014    2015    2018    2019    2020    2021    2022    2023    2025    2026    2028    2033    2034    2036    2038    2042    2043    2046    2048    2050    2052    2053    2054    2058    2059    2060    2064    2065    2066    2067    2068    2069    2070    2071    2072    2076    2077    2078    2080    2081    2082    2083    2085    2087    2088    2089    2090    2091    2092    2093    2094    2096    2097    2099    2100    2102    2105    2106    2107    2108    2109    2110    2111    2112    2114    2115    2116    2117    2118    2119    2120    2121    2122    2123    2124    2125    2126    2130    2132    2133    2134    2135    2136    2137    2138    2139    2140    2141    2142    2143    2144    2145    2146    2147    2148    2150    2151    2153    2154    2155    2159    2160    2161    2162    2163    2167    2169    2171    2174    2176    2178    2181    2183    2184    2186    2188    2193    2194    2195    2202    2203    2206    2208    2212    2231    2232    2236    2240    2243    2245    2247    2248    2249    2252    2253    2259    2261    2262    2263    2266    2268    2269    2273    2278    2279    2282    2287    2288    2289    2290    2291    2294    2296    2297    2300    2301    2302    2303    2311    2312    2313    2315    2316    2318    2320    2321    2322    2324    2325    2328    2329    2331    2333    2334    2335    2336    2337    2338    2340    2344    2346    2348    2349    2351    2352    2353    2354    2355    2356    2357    2359    2360    2361    2363    2366    2367    2369    2371    2372    2373    2374    2375    2376    2377    2378    2379    2380    2381    2382    2383    2384    2387    2389    2390    2391    2392    2393    2394    2395    2396    2398    2399    2401    2402    2403    2404    2405    2406    2407    2408    2409    2410    2411    2412    2413    2414    2416    2420    2421    2422    2423    2424    2427    2428    2429    2431    2432    2433    2436    2439    2442    2443    2447    2448    2450    2453    2454    2455    2456    2457    2459    2463    2467    2468    2469    2470    2471    2473    2474    2476    2478    2485    2488    2490    2496    2497    2501    2502    2504    2505    2506    2511    2513    2517    2518    2520    2524    2527    2528    2529    2530    2531    2532    2533    2539    2540    2541    2542    2546    2549    2550    2551    2553    2555    2558    2560    2561    2565    2567    2568    2571    2572    2574    2575    2579    2580    2581    2583    2594    2596    2598    2599    2600    2605    2606    2611    2612    2613    2615    2616    2617    2618    2622    2628    2633    2639    2640    2641    2642    2643    2644    2648    2657    2660    2662    2664    2668    2670    2671    2672    2676    2677    2683    2686    2687    2688    2690    2692    2693    2694    2696    2699    2700    2701    2702    2706    2707    2709    2710    2712    2713    2716    2717    2718    2719    2720    2722    2723    2724    2726    2728    2729    2730    2731    2732    2734    2735    2736    2739    2745    2746    2747    2750    2759    2761    2762    2763    2764    2770    2771    2772    2779    2787    2788    2789    2791    2792    2793    2794    2795    2796    2797    2798    2799    2802    2803    2804    2805    2806    2807    2808    2810    2815    2819    2822    2826    2827    2829    2836    2840    2841    2843    2846    2852    2857    2858    2859    2860    2861    2862    2863    2866    2867    2870    2871    2872    2875    2877    2881    2883    2888    2889    2890    2891    2901    2902    2905    2906    2907    2908    2912    2915    2916    2917    2918    2919    2920    2921    2922    2924    2926    2929    2932    2935    2936    2940    2941    2942    2944    2946    2947    2948    2949    2950    2951    2952    2953    2959    2961    2966    2968    2970    2971    2973    2976    2985    2986    2987    2989    2990    2991    2993    2995    2997    3000    3004    3005    3006    3007    3011    3015    3016    3018    3019    3020    3022    3030    3032    3033    3034    3035    3036    3037    3039    3040    3044    3051    3052    3053    3054    3060    3061    3062    3063    3066    3067    3068    3070    3071    3072    3074    3075    3077    3079    3081    3082    3083    3087    3088    3089    3090    3091    3093    3095    3097    3098    3099    3100    3101    3102    3104    3105    3107    3108    3111    3113    3114    3125    3129    3130    3134    3135    3142    3145    3146    3147    3148    3152    3153    3155    3156    3157    3159    3160    3163    3167    3168    3169    3173    3174    3175    3176    3177    3178    3179    3181    3185    3186    3189    3194    3196    3197    3198    3200    3201    3203    3204    3208    3210    3213    3219    3238    3243    3244    3246    3247    3248    3249    3250    3251    3252    3253    3254    3255    3256    3257    3258    3259    3260    3261    3262    3263    3264    3265    3266    3267    3268    3269    3270    3271    3272    3273    3274    3275    3285    3296    3298    3300    3301    3307    3308    3316    3317    3324    3328    3334    3342    3347    3354    3355    3358    3359    3360    3361    3362    3363    3364    3365    3384    3386    3387    3388    3392    3394    3396    3397    3398    3404    3408    3409    3418    3420    3421    3424    3426    3429    3430    3435    3438    3439    3440    3441    3444    3448    3450    3451    3452    3461    3462    3466    3467    3468    3469    3471    3476    3477    3478    3479    3480    3481    3483    3484    3489    3494    3498    3499    3503    3504    3505    3507    3508    3510    3512    3513    3515    3519    3521    3524    3525    3526    3527    3528    3529    3534    3535    3536    3538    3543    3545    3546    3548    3549    3551    3552    3554    3555    3556    3564    3565    3566    3576    3578    3591    3593    3594    3598    3608    3614    3615    3616    3617    3618    3623    3624    3629    3633    3635    3638    3639    3646    3649    3654    3668    3671    3675    3676    3677    3681    3682    3683    3684    3685    3686    3688    3693    3697    3698    3699    3700    3701    3702    3703    3704    3705    3706    3707    3708    3712    3717    3723    3727    3729    3730    3733    3735    3740    3741    3742    3744    3745    3751    3752    3753    3754    3755    3760    3763    3764    3770    3783    3784    3785    3786    3788    3791    3793    3798    3799    3801    3802    3809    3811    3812    3814    3819    3821    3824    3825    3826    3827    3831    3836    3841    3844    3852    3861    3863    3864    3868    3869    3871    3873    3877    3879    3882    3889    3893    3896    3897    3908    3910    3911    3916    3917    3918    3925    3927    3930    3932    3946    3948    3949    3950    3952    3953    3959    3967    3968    3969    3972    3973    3977    3978    3979    3980    3981    3983    3984    3986    3987    3988    3991    3993    3994    3996    3997    3998    3999    4002    4005    4006    4007    4008    4010    4011    4014    4015    4016    4017    4018    4019    4020    4022    4023    4025    4027    4029    4030    4031    4033    4034    4036    4037    4039    4040    4041    4047    4052    4054    4056    4061    4062    4066    4069    4084    4085    4086    4090    4091    4102    4103    4104    4105    4117    4121    4124    4128    4132    4133    4144    4148    4149    4155    4159    4161    4167    4205    4207    4210    4211    4214    4215    4220    4223    4225    4226    4228    4232    4234    4235    4238    4239    4246    4247    4248    4254    4255    4262    4265    4270    4275    4280    4291    4292    4299    4306    4308    4310    4321    4322    4326    4327    4329    4333    4340    4343    4344    4349    4351    4356    4359    4361    4366    4367    4368    4369    4370    4372    4378    4380    4386    4387    4388    4396    4406    4424    4427    4443    4446    4447    4448    4464    4465    4467    4474    4478    4487    4488    4489    4499    4506    4508    4519    4533    4535    4544    4545    4546    4553    4558    4564    4571    4572    4587    4616    4621    4623    4638    4639    4641    4642    4643    4654    4661    4673    4677    4678    4679    4681    4700    4701    4703    4713    4718    4719    4720    4728    4733    4734    4735    4744    4748    4754    4757    4776    4787    4799    4809    4814    4815    4816    4821    4823    4835    4844    4846    4848    4855    4857    4865    4866    4867    4873    4874    4876    4878    4880    4881    4886    4887    4889    4890    4896    4901    4902    4903    4914    4936    4941    4951    4954    4958    4963    4967    4970    4973    4974    4975    4978    4979    4980    4990    4992    4993    4994    4995    5008    5009    5010    5013    5014    5015    5016    5025    5026    5027    5040    5047    5049    5055    5060    5064    5065    5066    5072    5093    5103    5107    5108    5110    5120    5128    5135    5139    5146    5147    5151    5152    5159    5171    5218    5219    5220    5222    5225    5247    5254    5265    5266    5267    5283    5291    5292    5293    5294    5296    5299    5303    5308    5309    5312    5313    5316    5319    5329    5349    5364    5377    5378    5380    5388    5391    5400    5401    5415    5418    5419    5420    5421    5444    5445    5446    5449    5452    5459    5463    5464    5478    5479    5481    5500    5502    5504    5505    5507    5508    5524    5528    5530    5540    5541    5572    5574    5577    5602    5608    5617    5618    5620    5621    5630    5650    5666    5668    5669    5673    5679    5690    5693    5747    5782    5784    5785    5791    5803    5810    5812    5816    5872    5876    5878    5881    5882    5899    5900    5902    5903    5941    5943    5944    5945    5952    5954    5955    5956    5957    5959    5970    5971    5989    5991    5992    5995    6001    6003    6006    6016    6058    6059    6062    6093    6104    6155    6156    6157    6166    6184    6187    6188    6212    6213    6214    6218    6238    6242    6250    6264    6281    6283    6286    6287    6294    6296    6297    6299    6301    6303    6305    6322    6323    6331    6333    6350    6365    6367    6370    6373    6377    6378    6380    6383    6385    6440    6461    6482    6502    6503    6534    6535    6537    6538    6539    6541    6548    6550    6552    6564    6565    6586    6593    6595    6615    6617    6618    6620    6639    6645    6659    6662    6663    6664    6669    6707    6708    6709    6711    6724    6731    6753    6754    6755    6764    6765    6773    6774    6787    6791    6793    6796    6807    6808    6810    6857    6863    6867    6870    6873    6874    6879    6880    6881    6888    6890    6893    6932    6934    6936    6942    6944    6947    6952    6953    6954    6957    6966    6979    6987    6993    6996    7000    7001    7004    7007    7013    7018    7022    7027    7034    7036    7044    7046    7063    7073    7076    7084    7090    7099    7101    7116    7121   

In [ ]:
target_user_df.shape

(1, 3133)

In [ ]:
# Step-3: Assign the films voted by the selected user to a list called movies_watched.

movies_watched_id = target_user_df.columns[target_user_df.notna().any()].to_list()
movies_watched_id

[1,
 3,
 7,
 17,
 52,
 62,
 135,
 140,
 141,
 260,
 494,
 628,
 648,
 653,
 708,
 719,
 733,
 736,
 743,
 762,
 780,
 788,
 802,
 1073]

In [ ]:
# Making a function to convert Movie Ids to Movie Titles

def convert_id_to_title (id_list):
    movie_titles = []
    for r in id_list:
            df1 = movie_df[movie_df['movieId']==r]
            title = df1['title'].values[0]
            movie_titles.append(title)
    return movie_titles

convert_id_to_title(movies_watched_id)

['Toy Story (1995)',
 'Grumpier Old Men (1995)',
 'Sabrina (1995)',
 'Sense and Sensibility (1995)',
 'Mighty Aphrodite (1995)',
 "Mr. Holland's Opus (1995)",
 'Down Periscope (1996)',
 'Up Close and Personal (1996)',
 'Birdcage, The (1996)',
 'Star Wars: Episode IV - A New Hope (1977)',
 'Executive Decision (1996)',
 'Primal Fear (1996)',
 'Mission: Impossible (1996)',
 'Dragonheart (1996)',
 'Truth About Cats & Dogs, The (1996)',
 'Multiplicity (1996)',
 'Rock, The (1996)',
 'Twister (1996)',
 'Spy Hard (1996)',
 'Striptease (1996)',
 'Independence Day (a.k.a. ID4) (1996)',
 'Nutty Professor, The (1996)',
 'Phenomenon (1996)',
 'Willy Wonka & the Chocolate Factory (1971)']

In [ ]:
len(movies_watched_id)

24

# Method 1 - Content-Based Filtering

In [ ]:
# Step-1: Find the id of the movie that the user has most recently rated 5

movie_id = half_rating_df[(half_rating_df["userId"] == target_user_id) & (half_rating_df["rating"] == 5.0)].sort_values(by="timestamp", ascending=False)["movieId"][0:1].values[0]

In [ ]:
# Step-2: Find the title of this movie

movie_title = movie_df[movie_df["movieId"] == movie_id]["title"].values[0]
movie_title

'Mighty Aphrodite (1995)'

In [ ]:
# Step-3: Create a dataframe for this movie

best_movie_df = movie_df[movie_df["movieId"] == movie_id]
best_movie_df

    movieId                    title                genres
51       52  Mighty Aphrodite (1995)  Comedy|Drama|Romance

In [ ]:
# Step 4: Get user's preferred genres based on their highly-rated movies

def get_user_preferred_genres(user_id, min_rating=4.0):
    # Get the movies rated by the user
    user_data = df[df['userId'] == user_id]

    # Filter for movies with a rating above the given threshold
    top_rated_movies = user_data[user_data['rating'] >= min_rating]

    # Get the genres of the top-rated movies
    preferred_genres = top_rated_movies['genres'].str.split('|').explode().unique()

    return preferred_genres

get_user_preferred_genres(target_user_id)

array(['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Sci-Fi', 'Thriller', 'Crime',
       'Mystery'], dtype=object)

In [ ]:
# Step 5: Filter unwatched movies based on preferred genres

def get_filtered_movies(user_id, preferred_genres):
    # Get the list of movies the user has already watched
    user_data = df[df['userId'] == user_id]
    user_watched_movies = user_data['movieId'].tolist()

    # Filter out movies the user has already watched
    unwatched_movies = movie_df[~movie_df['movieId'].isin(user_watched_movies)]

    # Further filter movies by matching genres
    filtered_movies = unwatched_movies[unwatched_movies['genres'].apply(
        lambda g: any(genre in g.split('|') for genre in preferred_genres)
    )]

    #Merge it with the best_movie to apply cosine similarity
    filtered_movies = pd.concat([filtered_movies, best_movie_df], ignore_index = True)
    filtered_movies.reset_index()

    return filtered_movies


a = get_filtered_movies(target_user_id, get_user_preferred_genres(target_user_id))

print("Filtered Movies Preview (head):")
print(a.head())

print("\nFiltered Movies Preview (tail):")
print(a.tail())

Filtered Movies Preview (head):
   movieId                               title                      genres
0        2                      Jumanji (1995)  Adventure|Children|Fantasy
1        4            Waiting to Exhale (1995)        Comedy|Drama|Romance
2        5  Father of the Bride Part II (1995)                      Comedy
3        6                         Heat (1995)       Action|Crime|Thriller
4        8                 Tom and Huck (1995)          Adventure|Children

Filtered Movies Preview (tail):
       movieId                          title                    genres
23960   131254   Kein Bund für's Leben (2007)                    Comedy
23961   131256  Feuer, Eis & Dosenbier (2002)                    Comedy
23962   131258             The Pirates (2014)                 Adventure
23963   131262               Innocence (2014)  Adventure|Fantasy|Horror
23964       52        Mighty Aphrodite (1995)      Comedy|Drama|Romance

In [ ]:
# Step 6: Make a function to apply content-based filtering

def get_content_based_recommendations_for_user(user_id, top_n=5, min_rating=4.0):
    # Get user's preferred genres
    preferred_genres = get_user_preferred_genres(user_id, min_rating)

    # Get filtered movies (unwatched by the user and matching preferred genres)
    filtered_df = get_filtered_movies(user_id, preferred_genres)

    # Create a new content DataFrame with only filtered unwatched movies
    content_df = filtered_df[['movieId', 'genres']]
    content_df['Content'] = content_df.fillna('').astype(str).agg(' '.join, axis=1)

    # Apply TF-IDF to this reduced set of movies
    tfidf_vectorizer = TfidfVectorizer()
    content_matrix = tfidf_vectorizer.fit_transform(content_df['Content'])

    # Cosine similarity calculation on the reduced set
    content_similarity = linear_kernel(content_matrix, content_matrix)

    # Get user's latest top-rated movie
    latest_top_rated_movie = movie_id

    # Get index of the latest top-rated movie in the reduced set
    movie_index = content_df[content_df['movieId'] == latest_top_rated_movie].index[0]

    # Get similarity scores for that movie
    similarity_scores = content_similarity[movie_index]

    # Sort and get top N similar movie indices (excluding the movie itself)
    similar_indices = similarity_scores.argsort()[::-1][1:top_n + 1]

    # Get the corresponding movie id of the recommendations
    recommendations_id = content_df.loc[similar_indices, 'movieId'].values

    return recommendations_id

In [ ]:
#Example Usage
cbf_recommendations = get_content_based_recommendations_for_user(user_id=target_user_id)
cbf_movieId = cbf_recommendations.tolist()

In [ ]:
print(cbf_movieId)

[4, 5, 103920, 103539, 103606]

In [ ]:
# Making a function to convert Movie Ids to Movie Titles & Genres

def convert_id_to_title_and_genre (id_list):
    recommendations = []
    for r in id_list:
            df1 = movie_df[movie_df['movieId']==r]
            title = df1['title'].values[0]
            genre = df1['genres'].values[0]
            recommendations.append((title, genre))

    for movie, genre in recommendations:
        print(f"Movie: {movie}, Genre: {genre}")

convert_id_to_title_and_genre(cbf_movieId)

Movie: Waiting to Exhale (1995), Genre: Comedy|Drama|Romance
Movie: Father of the Bride Part II (1995), Genre: Comedy
Movie: All Together, The (2007), Genre: Comedy|Drama|Romance
Movie: The Spectacular Now (2013), Genre: Comedy|Drama|Romance
Movie: Stuck in Love (2012), Genre: Comedy|Drama|Romance

# Method 2 - Collaborative Filtering

## 2.1 Correlation Method - Pearson's Correlation Coefficient

### Accessing Data and Ids of Other Users Watching the Same Films

In [ ]:
# Step-1: Create a new dataframe containing only the films watched by the selected user.

movies_watched_df = user_movie_df[movies_watched_id]

In [ ]:
movies_watched_df.tail()

movieId   1     3     7     17    52    62    135   140   141   260   494   628   648   653   708   719   733   736   743   762   780   788   802   1073
userId
138485.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
138486.0   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.5   NaN   NaN   NaN   NaN   4.5   NaN   NaN   5.0   NaN   NaN   4.5
138487.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
138488.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
138490.0   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

In [ ]:
movies_watched_df.shape

(69246, 24)

In [ ]:
# Step-2: Create a new dataframe, user_movie_count, showing how many films each user has also watched
#         from the selected user's film list.

user_movie_count = movies_watched_df.T.notnull().sum()

In [ ]:
user_movie_count = user_movie_count.reset_index()

In [ ]:
user_movie_count.columns = ["userId", "movie_count"]

In [ ]:
user_movie_count.tail(10)

         userId  movie_count
69236  138476.0            0
69237  138481.0            1
69238  138482.0            1
69239  138483.0            8
69240  138484.0            6
69241  138485.0            0
69242  138486.0            5
69243  138487.0            0
69244  138488.0            1
69245  138490.0            1

In [ ]:
# Step-3: Identify users who have watched at least 50% of the films watched by the selected user.
#         These users are considered similar to the selected user.

perc = len(movies_watched_id) * 50 / 100

In [ ]:
users_same_movies = user_movie_count[user_movie_count["movie_count"] > perc]["userId"]

In [ ]:
len(users_same_movies)

4112

### Determining the Users Most Similar to the User to Make Suggestion

In [ ]:
# Step-4: Filter movies_watched_df to retain only the Ids of similar users.

final_df = movies_watched_df[movies_watched_df.index.isin(users_same_movies)]

In [ ]:
final_df.head()

movieId  1     3     7     17    52    62    135   140   141   260   494   628   648   653   708   719   733   736   743   762   780   788   802   1073
userId
6.0       5.0   3.0   5.0   5.0   5.0   5.0   3.0   4.0   5.0   4.0   4.0   4.0   5.0   4.0   4.0   3.0   3.0   2.0   3.0   3.0   3.0   4.0   3.0   1.0
19.0      5.0   4.0   5.0   4.0   NaN   5.0   4.0   NaN   5.0   NaN   4.0   4.0   3.0   NaN   NaN   3.0   4.0   4.0   NaN   NaN   4.0   4.0   4.0   5.0
54.0      4.0   NaN   NaN   2.0   4.0   NaN   2.0   NaN   NaN   4.0   4.0   NaN   3.0   NaN   3.0   3.0   4.0   4.0   NaN   NaN   5.0   3.0   NaN   3.0
69.0      4.0   NaN   NaN   NaN   NaN   3.0   2.0   NaN   NaN   5.0   3.0   NaN   4.0   2.0   3.0   4.0   4.0   3.0   2.0   3.0   4.0   3.0   NaN   4.0
143.0     4.0   3.0   4.0   NaN   NaN   NaN   NaN   NaN   5.0   4.0   4.0   4.0   4.0   3.0   NaN   3.0   4.0   3.0   NaN   NaN   4.0   4.0   3.0   3.0

In [ ]:
final_df.shape

(4112, 24)

In [ ]:
# Step-5: Create a new dataframe, corr_df, containing correlation scores between the selected user
#         and other users based on their film ratings.

corr_df = final_df.T.corr().unstack().sort_values()

In [ ]:
corr_df = pd.DataFrame(corr_df, columns=["corr"])

In [ ]:
corr_df.head()

                  corr
userId  userId
31080.0 62702.0   -1.0
23375.0 128356.0  -1.0
99958.0 1301.0    -1.0
62702.0 31080.0   -1.0
60705.0 128690.0  -1.0

In [ ]:
corr_df.index.names = ['user_id_1', 'user_id_2']

In [ ]:
corr_df = corr_df.reset_index()

In [ ]:
# Step-6: Create a dataframe, top_users, to store users with a high correlation (above 0.5) with the selected user.
#         Sort by correlation in descending order.

top_users = corr_df[(corr_df["user_id_1"] == target_user_id) & (corr_df["corr"] >= 0.5)][["user_id_2", "corr"]].reset_index(drop=True)

In [ ]:
top_users = top_users.sort_values(by='corr', ascending=False)

In [ ]:
top_users.rename(columns={"user_id_2": "userId"}, inplace=True)

In [ ]:
top_users

       userId      corr
240       6.0  1.000000
239   57612.0  0.835603
238   98211.0  0.832822
237   43852.0  0.823816
236   11050.0  0.804650
235   69887.0  0.786947
234  122189.0  0.785424
233   20506.0  0.771112
232  113797.0  0.763969
231   35120.0  0.758340
230   37056.0  0.757961
229    6974.0  0.746967
228   54451.0  0.744500
227   39647.0  0.727253
226   36843.0  0.726418
225   53258.0  0.721840
224  106184.0  0.719890
223   49837.0  0.718063
222   95993.0  0.715929
221  125978.0  0.714265
220   37311.0  0.713200
219   70871.0  0.710047
218   77695.0  0.696039
217  117274.0  0.695046
216    3227.0  0.694588
215   90106.0  0.694310
214   99958.0  0.690130
213   15332.0  0.689062
212     143.0  0.687546
211   76714.0  0.677037
210    7204.0  0.671855
209   35253.0  0.668842
208   73057.0  0.667244
207  120354.0  0.663578
206   17391.0  0.663421
205   76735.0  0.660586
204  135394.0  0.658737
203  104815.0  0.658221
202   62818.0  0.654401
201   39899.0  0.654070
200   52075.0  0.652633
199   43412.0  0.651439
198   17587.0  0.649786
197   39931.0  0.648801
196   16765.0  0.647499
195   76595.0  0.641689
194   30622.0  0.639930
193   43386.0  0.639756
192   52241.0  0.638974
191   50259.0  0.637099
190    2902.0  0.635730
189  135531.0  0.633431
188   38139.0  0.633360
187  137387.0  0.631078
186  119591.0  0.629253
185  112582.0  0.629067
184   26830.0  0.628403
183   56674.0  0.627448
182   93021.0  0.626938
181  112093.0  0.622310
180    6812.0  0.622047
179   28971.0  0.621799
178   38492.0  0.621242
177  128224.0  0.620453
176   60401.0  0.617955
175    3890.0  0.617213
174  136599.0  0.616336
173   21540.0  0.616292
172   94882.0  0.614737
171   68227.0  0.614577
170   20701.0  0.614540
169     158.0  0.613279
168  136897.0  0.611558
167   78685.0  0.608998
166   28771.0  0.607052
165    2700.0  0.602102
164   30901.0  0.601338
163   48703.0  0.600925
162   49429.0  0.600650
161   35091.0  0.597687
160  121814.0  0.597129
159   59297.0  0.596712
158  108332.0  0.594294
157   60769.0  0.592463
156   55102.0  0.591608
155  118089.0  0.591377
154  122732.0  0.590624
153   89783.0  0.590472
152  112406.0  0.589158
151   58679.0  0.587958
150   98875.0  0.586053
149  129970.0  0.585206
148   56718.0  0.583618
147  115855.0  0.583515
146   12772.0  0.583108
145  113235.0  0.582298
144   24113.0  0.581559
143  111214.0  0.580389
142   79557.0  0.580389
141  109062.0  0.579659
140  116904.0  0.579572
139  101856.0  0.579521
138   79665.0  0.579438
137   48466.0  0.577152
136   63758.0  0.576719
135   51750.0  0.575986
134  118138.0  0.572424
133   83340.0  0.571929
132   77923.0  0.571361
131  137448.0  0.570787
130  128050.0  0.568038
129  126060.0  0.566947
128  116724.0  0.566679
127   51275.0  0.566177
126    2532.0  0.565066
125   18706.0  0.564009
124  120126.0  0.563932
123  137147.0  0.563464
122  105985.0  0.562926
121  130622.0  0.562447
120   37780.0  0.562409
119   49758.0  0.562092
118  105608.0  0.561194
117   46885.0  0.560607
116   78262.0  0.559592
115   66617.0  0.559118
114   70403.0  0.558069
113  123360.0  0.557727
112  114842.0  0.557165
111   99099.0  0.555959
110   91110.0  0.555626
109   68710.0  0.555527
108   57896.0  0.554883
107   10230.0  0.554114
106   57491.0  0.553899
105   83343.0  0.553245
104   22211.0  0.551623
103   22527.0  0.551383
102   42424.0  0.549454
101   32838.0  0.548991
100  105877.0  0.547723
99   101770.0  0.547619
98    39580.0  0.547509
97    76640.0  0.547365
96   111055.0  0.546618
95    94773.0  0.546465
94    16793.0  0.546413
93    53619.0  0.546020
92    74071.0  0.545581
91   113487.0  0.544475
90    44853.0  0.543489
89   131777.0  0.542897
88    98799.0  0.542114
87    25704.0  0.541599
86    87703.0  0.540921
85    11421.0  0.540895
84    39154.0  0.540562
83    68002.0  0.539906
82    99654.0  0.539603
81    25827.0  0.539396
80    21096.0  0.539360
79   108560.0  0.539234
78    87617.0  0.539139
77   134075.0  0.538454
76   122919.0  0.538382
75     3926.0  0.538066
74    68026.0  0.537742
73    97397.0  0.537278
72    53998.0  0.536783
71    55456.0  0.536745
70    61375.0  0.536513
69   134675.0  0.536458
68    76677.0  0.535915
67     8761.0  0.535463
66    69426.0  0.535239
65    66435.0  0.534091
64    61637.0  0.532943
63     7674.0  0.532208
62   100358.0  0.531741
61     5674.0  0.531489
60    49392.0  0.531394
59    89049.0  0.531249
58    35709.0  0.530994
57    63882.0  0.530330
56    15818.0  0.529731
55   103869.0  0.529368
54    31753.0  0.529150
53   119612.0  0.528252
52    91817.0  0.528068
51    38267.0  0.527972
50    53556.0  0.526530
49    61841.0  0.525596
48    23809.0  0.525487
47   133725.0  0.525419
46    87442.0  0.524142
45     6921.0  0.523660
44   123861.0  0.523291
43   110445.0  0.522963
42   129851.0  0.522513
41    59101.0  0.522233
40   124954.0  0.521363
39   102317.0  0.519784
38    98052.0  0.519460
37    47902.0  0.519370
36   118596.0  0.518961
35   125268.0  0.517749
34    34285.0  0.515789
33    15720.0  0.515729
32    75828.0  0.515482
31    58801.0  0.514969
30    85451.0  0.513892
29    79381.0  0.513655
28     5843.0  0.512858
27    18895.0  0.512686
26   101768.0  0.512396
25   138148.0  0.512348
24    80556.0  0.512052
23    76921.0  0.511838
22     7036.0  0.510909
21    15203.0  0.507621
20   128047.0  0.507368
19    11246.0  0.507300
18   100194.0  0.507281
17     1625.0  0.506958
16    25770.0  0.505551
15   102300.0  0.505435
14   103373.0  0.504919
13    53640.0  0.504172
12   129435.0  0.504082
11   101577.0  0.504058
10    30699.0  0.503953
9    120572.0  0.503861
8     26628.0  0.502295
7    108195.0  0.501820
6    124764.0  0.501140
5      9146.0  0.500694
4    103428.0  0.500694
3     42803.0  0.500639
2     23375.0  0.500626
1     12793.0  0.500588
0     86621.0  0.500035

In [ ]:
top_users.shape

(241, 2)

In [ ]:
# Step-7: Merge the top_users dataframe with the ratings dataset to access ratings given by highly correlated users.
#         Exclude the target user from the merged data.

top_users_ratings = top_users.merge(rating_df[["userId", "movieId", "rating"]], how='inner')

In [ ]:
top_users_ratings = top_users_ratings[top_users_ratings["userId"] != target_user_id]

In [ ]:
top_users_ratings["userId"].unique()

array([ 57612.,  98211.,  43852.,  11050.,  69887., 122189.,  20506.,
       113797.,  35120.,  37056.,   6974.,  54451.,  39647.,  36843.,
        53258., 106184.,  49837.,  95993., 125978.,  37311.,  70871.,
        77695., 117274.,   3227.,  90106.,  99958.,  15332.,    143.,
        76714.,   7204.,  35253.,  73057., 120354.,  17391.,  76735.,
       135394., 104815.,  62818.,  39899.,  52075.,  43412.,  17587.,
        39931.,  16765.,  76595.,  30622.,  43386.,  52241.,  50259.,
         2902., 135531.,  38139., 137387., 119591., 112582.,  26830.,
        56674.,  93021., 112093.,   6812.,  28971.,  38492., 128224.,
        60401.,   3890., 136599.,  21540.,  94882.,  68227.,  20701.,
          158., 136897.,  78685.,  28771.,   2700.,  30901.,  48703.,
        49429.,  35091., 121814.,  59297., 108332.,  60769.,  55102.,
       118089., 122732.,  89783., 112406.,  58679.,  98875., 129970.,
        56718., 115855.,  12772., 113235.,  24113., 111214.,  79557.,
       109062., 116904., 101856.,  79665.,  48466.,  63758.,  51750.,
       118138.,  83340.,  77923., 137448., 128050., 126060., 116724.,
        51275.,   2532.,  18706., 120126., 137147., 105985., 130622.,
        37780.,  49758., 105608.,  46885.,  78262.,  66617.,  70403.,
       123360., 114842.,  99099.,  91110.,  68710.,  57896.,  10230.,
        57491.,  83343.,  22211.,  22527.,  42424.,  32838., 105877.,
       101770.,  39580.,  76640., 111055.,  94773.,  16793.,  53619.,
        74071., 113487.,  44853., 131777.,  98799.,  25704.,  87703.,
        11421.,  39154.,  68002.,  99654.,  25827.,  21096., 108560.,
        87617., 134075., 122919.,   3926.,  68026.,  97397.,  53998.,
        55456.,  61375., 134675.,  76677.,   8761.,  69426.,  66435.,
        61637.,   7674., 100358.,   5674.,  49392.,  89049.,  35709.,
        63882.,  15818., 103869.,  31753., 119612.,  91817.,  38267.,
        53556.,  61841.,  23809., 133725.,  87442.,   6921., 123861.,
       110445., 129851.,  59101., 124954., 102317.,  98052.,  47902.,
       118596., 125268.,  34285.,  15720.,  75828.,  58801.,  85451.,
        79381.,   5843.,  18895., 101768., 138148.,  80556.,  76921.,
         7036.,  15203., 128047.,  11246., 100194.,   1625.,  25770.,
       102300., 103373.,  53640., 129435., 101577.,  30699., 120572.,
        26628., 108195., 124764.,   9146., 103428.,  42803.,  23375.,
        12793.,  86621.])

In [ ]:
top_users_ratings.head()

     userId      corr  movieId  rating
24  57612.0  0.835603        1     4.0
25  57612.0  0.835603        3     3.0
26  57612.0  0.835603        7     5.0
27  57612.0  0.835603       11     5.0
28  57612.0  0.835603       17     5.0

### Calculation of Weighted Average Recommendation Score

In [ ]:
# Step-8: Create a new column, weighted_rating, which is the product of each user's correlation score
#         and their rating for a given movie.

top_users_ratings['weighted_rating'] = top_users_ratings['corr'] * top_users_ratings['rating']

In [ ]:
top_users_ratings.head()

     userId      corr  movieId  rating  weighted_rating
24  57612.0  0.835603        1     4.0         3.342410
25  57612.0  0.835603        3     3.0         2.506808
26  57612.0  0.835603        7     5.0         4.178013
27  57612.0  0.835603       11     5.0         4.178013
28  57612.0  0.835603       17     5.0         4.178013

In [ ]:
# Step-9: Create a new dataframe, recommendation_df, with movie ids and the average weighted ratings
#         across all similar users for each movie.

recommendation_df = top_users_ratings.groupby('movieId').agg({"weighted_rating": "mean"})

In [ ]:
recommendation_df = recommendation_df.reset_index()

In [ ]:
recommendation_df.sort_values("weighted_rating", ascending=False).head()

      movieId  weighted_rating
2843     3446         3.855560
7244    33826         3.636264
4556     5681         3.636264
3428     4183         3.590262
7471    41714         3.571325

In [ ]:
# Step-10: Filter movies with an average weighted rating above 3 and that are not watched by the selected user.
#          Sort them by weighted rating in descending order to get the best recommendations.

recommendation_df = recommendation_df[(recommendation_df["weighted_rating"] > 3) & (~recommendation_df['movieId'].isin(movies_watched_id))].sort_values("weighted_rating", ascending=False)

recommendation_df.head()

      movieId  weighted_rating
2843     3446         3.855560
4556     5681         3.636264
7244    33826         3.636264
3428     4183         3.590262
6662    26501         3.571325

In [ ]:
# Step-11: Select the top 5 movies with the highest average weighted ratings as recommendations.

corr_recommendations = recommendation_df.sort_values("weighted_rating", ascending=False)[:5]
print(corr_recommendations)

      movieId  weighted_rating
2843     3446         3.855560
7244    33826         3.636264
4556     5681         3.636264
3428     4183         3.590262
8479    61373         3.571325

In [ ]:
corr_movieId = corr_recommendations['movieId'].tolist()
print(corr_movieId)

[3446, 33826, 5681, 4183, 61373]

In [ ]:
# Get the corresponding movie title & genre of the recommendations

convert_id_to_title_and_genre(corr_movieId)

Movie: Funny Bones (1995), Genre: Comedy|Drama
Movie: Saint Ralph (2004), Genre: Comedy|Drama
Movie: Fidel (2001), Genre: Documentary
Movie: Unbelievable Truth, The (1989), Genre: Comedy|Drama
Movie: Woman in Black, The (1989), Genre: Horror|Mystery

## 2.2 Matrix Factorization Method - Singular Value Decomposition

In [ ]:
# Step 1: Define the reader to specify the rating scale

reader = Reader(rating_scale=(0.5, 5.0))

# Step 2: Load the dataset into Surprise format

data = Dataset.load_from_df(common_movies[['userId', 'movieId', 'rating']], reader)

# Step 3: Split the data into training and testing sets

trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

# Step 4: Initialize the SVD model

svd_model = SVD()

# Step 5: Train the model on the training set

svd_model.fit(trainset)

In [ ]:
# Step 6: Predict ratings for the test set and calculate RMSE to evaluate the model

predictions = svd_model.test(testset)
rmse = accuracy.rmse(predictions)

RMSE: 0.7873

In [ ]:
# Step 7: Define a function to get recommendations for a specific user

def get_user_recommendations(user_id, top_n=5):
    # Get all movies rated by the user
    user_rated_movies = common_movies[common_movies['userId'] == user_id]['movieId'].tolist()

    # Predict ratings for all movies the user hasn't rated yet
    movie_predictions = [
        (movie_id, svd_model.predict(user_id, movie_id).est)
        for movie_id in common_movies['movieId'].unique()
        if movie_id not in user_rated_movies
    ]

    # Sort predictions by estimated rating in descending order and select the top N
    movie_predictions.sort(key=lambda x: x[1], reverse=True)
    top_movies = movie_predictions[:top_n]

    return top_movies

In [ ]:
# Get recommendations for a specific user

svd_recommendations = get_user_recommendations(target_user_id)
svd_movieId = [i[0] for i in svd_recommendations]
print(svd_movieId)

[92259, 318, 110, 26614, 1221]

In [ ]:
# Get the corresponding movie title & genre of the recommendations

convert_id_to_title_and_genre(svd_movieId)

Movie: Intouchables (2011), Genre: Comedy|Drama
Movie: Shawshank Redemption, The (1994), Genre: Crime|Drama
Movie: Braveheart (1995), Genre: Action|Drama|War
Movie: Bourne Identity, The (1988), Genre: Action|Adventure|Drama|Mystery|Thriller
Movie: Godfather: Part II, The (1974), Genre: Crime|Drama

# Hybrid Recommendation

In [ ]:
# Step 1: Filter ratings for movie IDs from all methods separately

cbf_filtered_ratings = rating_df[rating_df['movieId'].isin(cbf_movieId)]
corr_filtered_ratings = rating_df[rating_df['movieId'].isin(corr_movieId)]
svd_filtered_ratings = rating_df[rating_df['movieId'].isin(svd_movieId)]

In [ ]:
svd_filtered_ratings.head()

     userId  movieId  rating            timestamp
12        1      318     4.0  2005-04-02 23:33:18
178       2      110     4.0  2000-11-21 15:30:58
247       3      318     5.0  1999-12-11 13:09:26
299       3     1221     5.0  1999-12-11 13:01:34
457       5      110     4.0  1996-12-25 15:26:09

In [ ]:
# Step 2: Calculate average ratings of these movies for their corresponding dataframes

cbf_average_ratings = cbf_filtered_ratings.groupby('movieId')['rating'].mean().reset_index()
corr_average_ratings = corr_filtered_ratings.groupby('movieId')['rating'].mean().reset_index()
svd_average_ratings = svd_filtered_ratings.groupby('movieId')['rating'].mean().reset_index()

In [ ]:
svd_average_ratings.head()

   movieId    rating
0      110  4.042534
1      318  4.446990
2     1221  4.275641
3    26614  4.031519
4    92259  4.132396

In [ ]:
# Step 3: Sort by average rating and get the 2 highest rated movies from each method

cbf_top_2 = cbf_average_ratings.sort_values(by='rating', ascending=False)[:2]
corr_top_2 = corr_average_ratings.sort_values(by='rating', ascending=False)[:2]
svd_top_2 = svd_average_ratings.sort_values(by='rating', ascending=False)[:2]

In [ ]:
cbf_top_2

   movieId    rating
3   103606  3.675258
2   103539  3.544601

In [ ]:
corr_top_2

   movieId    rating
1     4183  3.854508
3    33826  3.601604

In [ ]:
svd_top_2

   movieId    rating
1      318  4.446990
2     1221  4.275641

In [ ]:
# Make a combined list of all these movie IDs

cbf_top_2_ids = cbf_top_2['movieId'].values.tolist()
corr_top_2_ids = corr_top_2['movieId'].values.tolist()
svd_top_2_ids = svd_top_2['movieId'].values.tolist()
final_recommendations_id = list(set(cbf_top_2_ids + corr_top_2_ids + svd_top_2_ids))
final_recommendations_id

[33826, 1221, 103539, 103606, 4183, 318]

In [ ]:
# Get the corresponding movie title & genre of the recommendations

convert_id_to_title_and_genre(final_recommendations_id)

Movie: Saint Ralph (2004), Genre: Comedy|Drama
Movie: Godfather: Part II, The (1974), Genre: Crime|Drama
Movie: The Spectacular Now (2013), Genre: Comedy|Drama|Romance
Movie: Stuck in Love (2012), Genre: Comedy|Drama|Romance
Movie: Unbelievable Truth, The (1989), Genre: Comedy|Drama
Movie: Shawshank Redemption, The (1994), Genre: Crime|Drama